version: '{build}'
branches:
  only:
  - master
clone_folder: C:/projects/bfa
image:
- Visual Studio 2015
- Ubuntu
configuration:
- Release
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

install:
- sh: cmake cmake-curses-gui

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Ubuntu" ( set generator="Unix Makefiles" )
- echo %generator%
- sh: sh build_files/build_environment/install_deps.sh --with-all --no-confirm

#    call build_files/build_environment/windows/install_cuda.cmd
before_build:
- cmd: |-
    cd ..
    if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/win64_vc14 lib/win64_vc14)
    cd bfa
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator%
    dir C:/projects/bfa/build/
build:
  project: C:/projects/bfa/build/bforartists.sln
  verbosity: minimal
  parallel: true
