schema_version = "1.0.0"
id = "copy_attributes_menu"
name = "Copy Attributes Menu"
version = "0.6.0"
tagline = "Copy Attributes Menu - Bforartists Version"
maintainer = "Community"
type = "add-on"
tags = ["User Interface"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://projects.blender.org/extensions/space_view3d_copy_attributes"
copyright = [
    "2024 Bassam Kurdali",
    "2024 Fabian Fricke",
    "2024 Adam Wiseman",
    "2024 Demeter Dzadik",
]
