name: BUILD-RELEASE

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  schedule:
    - cron: 0 0 * * 1
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]

    steps:

      - name : Setup Environment Variables
        shell: python
        run: |
          import os
          from os import path
          main_dir = path.join(os.getcwd(),'..')
          main_dir = path.abspath(main_dir)
          print("::stop-commands::'::set-env name=_MAIN_DIR::{}'".format(main_dir))

      - name: Cache build environment
        uses: actions/cache@v2
        env:
          cache-name: ${{ github.ref }}-${{ runner.os }}
          path: ${{ env._MAIN_DIR }}
        with:
          path: ${{ env._MAIN_DIR }}
          key: build-cache-${{ env.cache-name }}

      - uses: actions/checkout@v2

      - name: Build.py
        run: python build.py

      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: Bforartists-Release-${{ runner.os }}
          path: ${{ env._MAIN_DIR }}/build_release/bin/
